blank_issues_enabled: false
contact_links:
  - name: Contact Us
    url: https://github.com/alvy023/patch-notes-delivered/discussions
    about: Please use Discussions or an issue template for any feedback or support.
