name: Check WoW Build

on:
  schedule:
    - cron: '30 7 * * *'  # every day at noon UTC
  workflow_dispatch:  # allows you to manually trigger the check

jobs:
  check_build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install requests

      - name: Run build check script
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: python scripts/check_wow_build.py
