name: Check WoW Version/Build

on:
  schedule:
    - cron: '30 19 * * *'  # Runs daily at 7:30 PM UTC
  workflow_dispatch:

jobs:
  check-version:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install requests

      - name: Run version check
        id: check_build
        run: |
          python scripts/check_build.py

      - name: Create PR for version update
        if: success() && steps.check_build.outcome == 'success'
        uses: peter-evans/create-pull-request@v5
        with:
          commit-message: "Update PatchNotesText.lua to latest build"
          branch: "update/patchnotes-$(date +'%Y%m%d%H%M%S')"
          title: "Update PatchNotesText.lua to latest build"
          body: "Automated update via workflow. Please review changes."
          labels: "automated-update"
