name: Create Patch Notes PR

on:
  # Manual Trigger, with input
  workflow_dispatch:
    inputs:
      notes:
        description: 'Notes file to update (optional - will use default if not provided)'
        required: false
        default: 'patch-11.1.7.lua'

  # Scheduled Trigger, Every Tuesday at 17:15 UTC (10:15 PST)
  schedule:
    - cron: '15 17 * * 2'

permissions:
  contents: write
  pull-requests: write

jobs:
  check-build:
    runs-on: ubuntu-latest

    env:
      NOTES_FILE: ${{ vars.NOTES_FILE }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          ref: dev

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.x

      - name: Install requests
        run: pip install requests

      - name: Run build check
        id: check_build
        run: |
          NOTES="${{ github.event.inputs.notes || env.NOTES_FILE }}"
          echo "Notes File: $NOTES"
          python .github/scripts/update_patch_notes.py "$NOTES"

      - name: Commit updated build number
        if: steps.check_build.outputs.updated == 'true'
        run: |
          NOTES="${{ github.event.inputs.notes || env.NOTES_FILE }}"
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add PatchNotesDelivered/notes/$NOTES
          git commit -m "Update $NOTES to latest build"

      - name: Check for existing Open Pull Request
        id: check_existing_pr
        if: steps.check_build.outputs.updated == 'true'
        run: |
          BRANCH_NAME="update/patchnotes-${{ steps.check_build.outputs.branch_name }}"
          # Check for OPEN pull requests originating from this branch
          if gh pr list --head "$BRANCH_NAME" --state open --json number --limit 1 | grep -q '[0-9]'; then
            echo "An open PR for branch $BRANCH_NAME already exists."
            echo "exists=true" >> $GITHUB_OUTPUT
          else
            echo "No open PR for branch $BRANCH_NAME found."
            echo "exists=false" >> $GITHUB_OUTPUT
          fi
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create Pull Request
        if: steps.check_build.outputs.updated == 'true' && steps.check_existing_pr.outputs.exists == 'false'
        uses: peter-evans/create-pull-request@v5
        with:
          commit-message: "Update notes file to latest build"
          title: "Update PatchNotesText.lua to latest build"
          body: "Automatically created PR to update to latest WoW build."
          branch: update/patchnotes-${{ steps.check_build.outputs.branch_name }}
          base: dev
