name: Promote Issue to Bug Branch

on:
  issues:
    types: [labeled]
  workflow_dispatch:

jobs:
  check-approved-label:
    runs-on: ubuntu-latest
    steps:
      - name: Check if the label is 'approved'
        if: github.event.label.name == 'approved'
        run: |
          # Get the username of the person who applied the label
          USER=$(jq --raw-output .sender.login "$GITHUB_EVENT_PATH")
          
          # Get the list of approved users
          IFS=',' read -r -a APPROVED_USERS <<< "${{ vars.APPROVED_USERS }}"
          
          # Check if the user applying the label is in the allowed list
          if [[ ! " ${APPROVED_USERS[@]} " =~ " ${USER} " ]]; then
            echo "User $USER is not allowed to add the 'approved' label."
            
            # Remove the 'approved' label if applied by a non-allowed user
            curl -X DELETE \
              -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
              "https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.issue.number }}/labels/approved"

            exit 1
          fi
          
  create-bug-branch:
    name: Create Bug Branch
    runs-on: ubuntu-latest
    if: github.event.label.name == 'approved' && contains(github.event.issue.labels.*.name, 'bug')
    steps:
      - name: Checkout dev branch
        uses: actions/checkout@v4
        with:
          ref: dev
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set Branch Prefix
        run: echo "BRANCH_PREFIX=bugs/bug" >> $GITHUB_ENV

      - name: Generate Branch Name
        run: |
          ISSUE_TITLE="${{ github.event.issue.title }}"
          ISSUE_NUMBER="${{ github.event.issue.number }}"
          # Remove [BUG]
          SAFE_TITLE=$(echo "$ISSUE_TITLE" | sed -E 's/^\[BUG\]\s*//')
          # Make title branch friendly
          SAFE_TITLE=$(echo "$SAFE_TITLE" | tr '[:upper:]' '[:lower:]' | tr -cs 'a-z0-9' '-' | sed 's/^-*//;s/-*$//')
          BRANCH_NAME="${BRANCH_PREFIX}-${SAFE_TITLE}-${ISSUE_NUMBER}"
          echo "Branch name: $BRANCH_NAME"
          echo "BRANCH_NAME=$BRANCH_NAME" >> $GITHUB_ENV

      - name: Create and Push Branch
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git checkout -b "$BRANCH_NAME"
          git push https://x-access-token:${GH_TOKEN}@github.com/alvy023/patch-notes-delivered.git "$BRANCH_NAME"

      - name: Comment on Issue
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh issue comment "${{ github.event.issue.number }}" --body "✅ A new branch [$BRANCH_NAME](https://github.com/${{ github.repository }}/tree/$BRANCH_NAME) has been created."
