name: Publish Retail Release

on:
  workflow_dispatch:
    inputs:
      upload_curseforge:
        description: 'Upload to CurseForge?'
        required: false
        default: 'true'
        type: boolean
      upload_wowup:
        description: 'Upload to WowUp?'
        required: false
        default: 'true'
        type: boolean

jobs:
  publish:
    name: Publish Addon to CurseForge and WowUp
    runs-on: ubuntu-latest

    env:
      ADDON_NAME: PatchNotesDelivered

    steps:
      - name: Checkout main
        uses: actions/checkout@v4
        with:
          ref: main
          submodules: recursive

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.x

      - name: Download latest release items from GitHub Releases
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          release_asset_name=$(gh release view --json assets --jq ".assets[].name")
          if [ -z "$release_asset_name" ]; then
            echo "No release asset found in latest release."
            exit 1
          fi
          gh release download --pattern "$release_asset_name" --dir dist
          gh release view --json body --jq ".body" > RELEASE_NOTES.md
          echo "release_asset_name=${release_asset_name}" >> $GITHUB_OUTPUT

      # CURSEFORGE UPLOAD (manual curl)
      - name: Upload to CurseForge
        if: ${{ github.event.inputs.upload_curseforge == 'true' }}
        env:
          CF_API_KEY: ${{ secrets.CURSEFORGE_API_KEY }}
          ADDON_ID: ${{ secrets.CURSEFORGE_PROJECT_ID }}
        run: |
          CHANGELOG="RELEASE_NOTES.md"
          curl -X POST "https://wow.curseforge.com/api/projects/${ADDON_ID}/upload-file" \
            -H "x-api-token: ${CF_API_KEY}" \
            -F "file=@${release_asset_name}" \
            -F "changelog=@${CHANGELOG}" \
            -F "changelogType=markdown" \
            -F "displayName=$(basename "${release_asset_name}" .zip)"

      # WOWUP UPLOAD (WowUp CLI)
      - name: Upload to WowUp (Wago API)
        if: ${{ github.event.inputs.upload_wowup == 'true' }}
        env:
          WOWUP_API_TOKEN: ${{ secrets.WOWUP_API_TOKEN }}
          WOWUP_ADDON_ID: ${{ secrets.WOWUP_ADDON_ID }}
        run: |
          RELEASE_LABEL="${release_asset_name}"
          CHANGELOG=$(cat RELEASE_NOTES.md)
          SUPPORTED_RETAIL_PATCH=$(grep -oP 'Patch -\[ \*\*\K[0-9]+\.[0-9]+\.[0-9]+(?=\*\* \]-)' RELEASE_NOTES.md | head -n1)
          echo "RELEASE_LABEL: $RELEASE_LABEL"
          echo "SUPPORTED_RETAIL_PATCH: $SUPPORTED_RETAIL_PATCH"
          echo "CHANGELOG: $CHANGELOG"
          ls -l dist/
          METADATA=$(jq -n \
            --arg label "$RELEASE_LABEL" \
            --arg stability "stable" \
            --arg changelog "$CHANGELOG" \
            --arg patch "$SUPPORTED_RETAIL_PATCH" \
            '{label: $label, stability: $stability, changelog: $changelog, supported_retail_patch: $patch}')
          echo "METADATA: $METADATA"
          curl -f -X POST \
            -F "metadata=$METADATA" \
            -F "file=@dist/$RELEASE_LABEL" \
            -H "authorization: Bearer $WOWUP_API_TOKEN" \
            -H "accept: application/json" \
            "https://addons.wago.io/api/projects/$WOWUP_ADDON_ID/version"
