name: Update Patch Notes Metadata

on:
  schedule:
    - cron: '30 19 * * 2'  # Every Tuesday at 19:30 UTC (12:30 PST)
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  check-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.x

      - name: Install requests
        run: pip install requests

      - name: Run build check
        id: check_build
        run: python .github/scripts/update_patch_notes.py

      - name: Commit updated build number
        if: steps.check_build.outputs.updated == 'true'
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add PatchNotesDelivered/PatchNotesText.lua
          git commit -m "Update PatchNotesText.lua to latest build"

      - name: Check for existing Open Pull Request
        id: check_existing_pr
        if: steps.check_build.outputs.updated == 'true'
        run: |
          BRANCH_NAME="update/patchnotes-${{ steps.check_build.outputs.branch_name }}"
          # Check for OPEN pull requests originating from this branch
          if gh pr list --head "$BRANCH_NAME" --state open --json number --limit 1 | grep -q '[0-9]'; then
            echo "An open PR for branch $BRANCH_NAME already exists."
            echo "exists=true" >> $GITHUB_OUTPUT
          else
            echo "No open PR for branch $BRANCH_NAME found."
            echo "exists=false" >> $GITHUB_OUTPUT
          fi
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create Pull Request
        if: steps.check_build.outputs.updated == 'true' && steps.check_existing_pr.outputs.exists == 'false'
        uses: peter-evans/create-pull-request@v5
        with:
          commit-message: "Update PatchNotesText.lua to latest build"
          title: "Update PatchNotesText.lua to latest build"
          body: "Automatically created PR to update to latest WoW build."
          branch: update/patchnotes-${{ steps.check_build.outputs.branch_name }}
